#!/usr/bin/env python3
"""
FlowLab Video Processing - Picture-in-Picture with Live Metrics

Creates a PiP video with simulation frames and an overlay graph showing
real-time metrics from the metrics.csv file.

Generated by: Mistral Vibe AI Assistant
Date: 2026-10-06
Purpose: Post-processing tool for FlowLab recording data

Usage:
    python create_pip_video.py /path/to/recording/ [--fps 30]

Author: FlowLab Project
"""

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from collections import deque, namedtuple
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import cv2
import matplotlib

matplotlib.use("Agg")  # Non-interactive backend
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.ticker import FuncFormatter, MaxNLocator

DEFAULT_FPS = 30
WINDOW_SECONDS = 4  # history shown in the graphs, in seconds of output video
REQUIRED_COLUMNS = ("frameNumber", "compressionError", "iteration")

# Overlay layout (top-left PiP)
GRAPH_WIDTH_FRAC = 0.30  # fraction of frame width
GRAPH_HEIGHT_FRAC = 0.35  # fraction of frame height
GRAPH_MIN_SIZE = (300, 200)  # (width, height) in pixels
GRAPH_X, GRAPH_Y = 20, 20  # offset from the top-left corner
GRAPH_MARGIN = 10  # minimum gap to the right/bottom frame edge
BACKDROP_RGBA = (0, 0, 0, 0.55)  # translucent dark panel behind the graphs
COMP_COLOR = "#ff4d4d"  # compression error
ITER_COLOR = "#4dff6a"  # solver iterations


class RecordingError(Exception):
    """A problem with the recording or environment that the user can fix."""


# --------------------------------------------------------------------------
# Input loading
# --------------------------------------------------------------------------


def _natural_key(path):
    """Sort key so frame_9999.png comes before frame_10000.png."""
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r"(\d+)", path.name)]


def load_recording(recording_dir):
    """Validate a recording directory and return (metrics DataFrame, sorted frame paths)."""
    recording_dir = Path(recording_dir)
    frames_dir = recording_dir / "frames"
    metrics_file = recording_dir / "metrics.csv"

    if not recording_dir.is_dir():
        raise RecordingError(f"Recording directory not found: {recording_dir}")
    if not frames_dir.is_dir():
        raise RecordingError(f"Frames directory not found: {frames_dir}")
    if not metrics_file.is_file():
        raise RecordingError(f"Metrics file not found: {metrics_file}")

    try:
        metrics = pd.read_csv(metrics_file)
    except Exception as e:
        raise RecordingError(f"Could not read {metrics_file}: {e}") from e

    if metrics.empty:
        raise RecordingError("No data in metrics.csv")

    missing = [c for c in REQUIRED_COLUMNS if c not in metrics.columns]
    if missing:
        raise RecordingError(
            f"metrics.csv is missing column(s): {', '.join(missing)} "
            f"(found: {', '.join(map(str, metrics.columns))})"
        )

    frame_files = sorted(frames_dir.glob("*.png"), key=_natural_key)
    if not frame_files:
        raise RecordingError(f"No PNG frames found in {frames_dir}")

    return metrics, frame_files


def _numeric_column(metrics, name):
    return pd.to_numeric(metrics[name], errors="coerce").to_numpy(dtype=float)


def _y_limits(values):
    """Fixed Y range for a whole recording: starts at 0, 5% headroom on top."""
    lo = min(0.0, float(np.nanmin(values))) if np.isfinite(values).any() else 0.0
    hi = float(np.nanmax(values)) * 1.05 if np.isfinite(values).any() else 1.0
    if not np.isfinite(hi) or hi <= lo:
        hi = lo + 1.0
    return lo, hi


def read_frames(paths, workers=4, ahead=8):
    """Yield decoded BGR frames in order (None if unreadable).

    PNG decoding runs in a few background threads, a bounded number of frames
    ahead, so it overlaps with graph rendering and encoding.
    """
    with ThreadPoolExecutor(max_workers=workers) as pool:
        pending = deque()
        remaining = iter(paths)
        for path in remaining:
            pending.append(pool.submit(cv2.imread, str(path)))
            if len(pending) >= ahead:
                break
        while pending:
            frame = pending.popleft().result()
            for path in remaining:  # top the queue back up by one
                pending.append(pool.submit(cv2.imread, str(path)))
                break
            yield frame


# --------------------------------------------------------------------------
# Graph overlay
# --------------------------------------------------------------------------


def _fmt(value):
    """Compact number format shared by tick labels and readouts."""
    return f"{value:.3g}" if np.isfinite(value) else "-"


_Trace = namedtuple("_Trace", "ax line head readout")


class MetricsOverlay:
    """
    Two scrolling traces on a translucent panel.

    The axes (grid, titles, tick labels) are static: they are rendered once and
    cached. Per frame, only the traces, head markers and readouts are redrawn on
    top of that cached background, so the data scrolls but nothing else moves.
    The newest sample is always at the right edge.
    """

    def __init__(self, width, height, dpi, window, step, comp_ylim, iter_ylim):
        span = (window - 1) * step  # x extent of the window, in frame-number units

        with plt.style.context("dark_background"):
            fig = plt.figure(figsize=(width / dpi, height / dpi), dpi=dpi)
            fig.patch.set_facecolor(BACKDROP_RGBA)
            fig.patch.set_visible(True)
            fig.subplots_adjust(left=0.11, right=0.97, top=0.88, bottom=0.13, hspace=0.58)
            ax_comp, ax_iter = fig.subplots(2, 1)

            specs = (
                (ax_comp, "Density Error", COMP_COLOR, comp_ylim, "default"),
                (ax_iter, "Pressure Solver Iterations", ITER_COLOR, iter_ylim, "steps-post"),
            )
            self._traces = []
            for ax, title, color, ylim, drawstyle in specs:
                ax.patch.set_visible(False)  # let the figure backdrop show through
                ax.set_xlim(-span, 0.02 * span)  # small right margin so the head dot isn't clipped
                ax.set_ylim(*ylim)
                ax.set_xticks(np.linspace(-span, 0, 5)[1:])  # fixed vertical gridlines, no labels
                ax.tick_params(axis="x", labelbottom=False, length=0)
                ax.tick_params(axis="y", labelsize=8)
                ax.yaxis.set_major_locator(MaxNLocator(nbins=4, integer=ax is ax_iter))
                ax.yaxis.set_major_formatter(FuncFormatter(lambda v, _pos: _fmt(v)))
                ax.grid(True, alpha=0.3, linewidth=0.5)
                ax.set_title(title, loc="left", fontsize=11, color=color)

                # Everything that changes per frame is "animated": skipped by the
                # full draw below and redrawn individually in render().
                (line,) = ax.plot([], [], color=color, linewidth=2, drawstyle=drawstyle, animated=True)
                (head,) = ax.plot([], [], "o", color=color, markersize=5, animated=True)
                readout = ax.annotate(
                    "", xy=(1.0, 1.0), xycoords="axes fraction",
                    xytext=(0, 6), textcoords="offset points",
                    ha="right", va="baseline", fontsize=10, color=color, animated=True,
                )  # fmt: skip
                self._traces.append(_Trace(ax, line, head, readout))

            self._frame_ax = ax_iter
            self._frame_label = ax_iter.annotate(
                "", xy=(0.5, 0.0), xycoords="axes fraction",
                xytext=(0, -6), textcoords="offset points",
                ha="center", va="top", fontsize=9, color="0.9", animated=True,
            )  # fmt: skip

        self.fig = fig
        fig.canvas.draw()  # static parts only
        self._background = fig.canvas.copy_from_bbox(fig.bbox)

    def render(self, rel_x, comp_values, iter_values, label):
        """Return the panel as an RGBA array for the current frame.

        rel_x holds frame numbers relative to the current frame (<= 0).
        """
        canvas = self.fig.canvas
        canvas.restore_region(self._background)
        for trace, values in zip(self._traces, (comp_values, iter_values)):
            trace.line.set_data(rel_x, values)
            trace.head.set_data(rel_x[-1:], values[-1:])
            trace.readout.set_text(_fmt(values[-1]))
            for artist in (trace.line, trace.head, trace.readout):
                trace.ax.draw_artist(artist)
        self._frame_label.set_text(label)
        self._frame_ax.draw_artist(self._frame_label)
        return np.asarray(canvas.buffer_rgba())

    def close(self):
        plt.close(self.fig)


def overlay_rgba(frame, rgba, x, y):
    """Alpha-blend a straight-alpha RGBA image onto a BGR frame in place."""
    h = min(rgba.shape[0], frame.shape[0] - y)
    w = min(rgba.shape[1], frame.shape[1] - x)
    rgba = rgba[:h, :w]
    roi = frame[y : y + h, x : x + w]

    alpha = rgba[..., 3:4].astype(np.float32) / 255.0
    bgr = rgba[..., 2::-1]  # RGB -> BGR
    roi[:] = (bgr * alpha + roi * (1.0 - alpha)).astype(np.uint8)


# --------------------------------------------------------------------------
# Video writers
# --------------------------------------------------------------------------


class _FfmpegWriter:
    """Pipes raw BGR frames to ffmpeg for H.264 output."""

    name = "ffmpeg (H.264)"

    def __init__(self, path, width, height, fps):
        cmd = [
            "ffmpeg", "-y", "-loglevel", "error",
            "-f", "rawvideo", "-pix_fmt", "bgr24",
            "-s", f"{width}x{height}", "-r", str(fps), "-i", "-",
            # yuv420p needs even dimensions; pad by at most one pixel if necessary
            "-vf", "pad=ceil(iw/2)*2:ceil(ih/2)*2",
            "-c:v", "libx264", "-crf", "18", "-pix_fmt", "yuv420p",
            "-movflags", "+faststart",
            str(path),
        ]  # fmt: skip
        self._err = tempfile.TemporaryFile()
        self._proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stderr=self._err)

    def _stderr(self):
        self._err.seek(0)
        return self._err.read().decode(errors="replace").strip()

    def write(self, frame):
        try:
            self._proc.stdin.write(frame.tobytes())
        except OSError as e:  # BrokenPipeError is a subclass
            self._proc.wait()
            raise RecordingError(f"ffmpeg stopped unexpectedly:\n{self._stderr()}") from e

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        if exc_type is not None:
            self._proc.kill()
            self._proc.wait()
            self._err.close()
            return False
        try:
            self._proc.stdin.close()
        except OSError:
            pass
        returncode = self._proc.wait()
        message = self._stderr()
        self._err.close()
        if returncode != 0:
            raise RecordingError(f"ffmpeg failed (exit code {returncode}):\n{message}")
        return False


class _OpenCvWriter:
    """Fallback when ffmpeg is unavailable: OpenCV's mp4v encoder."""

    name = "OpenCV (mp4v)"

    def __init__(self, path, width, height, fps):
        fourcc = cv2.VideoWriter_fourcc(*"mp4v")
        self._out = cv2.VideoWriter(str(path), fourcc, fps, (width, height))
        if not self._out.isOpened():
            raise RecordingError("Could not open video writer")

    def write(self, frame):
        self._out.write(frame)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        self._out.release()
        return False


def open_writer(path, width, height, fps):
    if shutil.which("ffmpeg"):
        return _FfmpegWriter(path, width, height, fps)
    print(
        "Warning: ffmpeg not found on PATH; falling back to OpenCV's mp4v encoder "
        "(larger files, lower quality).",
        file=sys.stderr,
    )
    return _OpenCvWriter(path, width, height, fps)


# --------------------------------------------------------------------------
# Main pipeline
# --------------------------------------------------------------------------


def create_pip_video(recording_dir, output_file, fps=DEFAULT_FPS):
    """
    Create Picture-in-Picture video with live metrics graph.

    Args:
        recording_dir: Path to FlowLab recording directory
        output_file: Output video path
        fps (int): Output frames per second

    Raises:
        RecordingError: if the recording or environment is unusable.
    """
    metrics, frame_files = load_recording(recording_dir)

    frame_no = _numeric_column(metrics, "frameNumber")
    comp = _numeric_column(metrics, "compressionError")
    iters = _numeric_column(metrics, "iteration")
    if np.isnan(frame_no).any():
        raise RecordingError("frameNumber column contains non-numeric values")

    # Metrics row i is paired with the i-th frame file (numeric filename order).
    num_frames = min(len(metrics), len(frame_files))
    if len(metrics) != len(frame_files):
        print(
            f"Warning: {len(metrics)} metrics rows but {len(frame_files)} frame files; "
            f"using the first {num_frames}."
        )

    first_frame = cv2.imread(str(frame_files[0]))
    if first_frame is None:
        raise RecordingError(f"Could not read first frame: {frame_files[0]}")
    height, width = first_frame.shape[:2]

    # Graph size: a fraction of the frame, with a minimum, clamped to fit.
    graph_w = max(int(width * GRAPH_WIDTH_FRAC), GRAPH_MIN_SIZE[0])
    graph_h = max(int(height * GRAPH_HEIGHT_FRAC), GRAPH_MIN_SIZE[1])
    graph_w = min(graph_w, width - GRAPH_X - GRAPH_MARGIN)
    graph_h = min(graph_h, height - GRAPH_Y - GRAPH_MARGIN)
    if graph_w < 100 or graph_h < 100:
        raise RecordingError(f"Frames are too small ({width}x{height}) for the overlay")

    # Render the panel at the exact overlay size (no resizing). Scale DPI with
    # the frame so text keeps its relative size on high-resolution recordings.
    dpi = max(100, round(100 * height / 1080))

    # Frame-number step per row, so the window width stays fixed even if frameNumber skips.
    diffs = np.diff(frame_no)
    step = float(np.median(diffs)) if diffs.size else 1.0
    if step <= 0:
        step = 1.0

    # History length is defined in seconds of video, so the on-screen scroll speed
    # is the same whatever the fps.
    window = max(10, round(WINDOW_SECONDS * fps))
    overlay = MetricsOverlay(graph_w, graph_h, dpi, window, step, _y_limits(comp), _y_limits(iters))

    print("Creating PiP video...")
    print(f"   Recording:   {recording_dir}")
    print(f"   Output:      {output_file}")
    print(f"   Frames:      {num_frames}")
    print(f"   FPS:         {fps}")
    print(f"   Resolution:  {width}x{height}")
    print(f"   Graph size:  {graph_w}x{graph_h} at ({GRAPH_X}, {GRAPH_Y})")
    print(f"   Window:      {window} frames ({WINDOW_SECONDS} s of video)")
    print()

    processed = 0
    unreadable = 0
    resized = 0

    try:
        with open_writer(output_file, width, height, fps) as writer:
            for i, frame in enumerate(read_frames(frame_files[:num_frames])):
                if frame is None:
                    unreadable += 1
                    continue
                if frame.shape[:2] != (height, width):
                    frame = cv2.resize(frame, (width, height), interpolation=cv2.INTER_AREA)
                    resized += 1

                lo = max(0, i - window + 1)
                rgba = overlay.render(
                    frame_no[lo : i + 1] - frame_no[i],
                    comp[lo : i + 1],
                    iters[lo : i + 1],
                    f"Frame {frame_no[i]:.0f}  |  last {window} frames",
                )
                overlay_rgba(frame, rgba, GRAPH_X, GRAPH_Y)

                writer.write(frame)
                processed += 1

                if (i + 1) % 50 == 0 or i == num_frames - 1:
                    print(f"   Progress: {i + 1}/{num_frames} frames ({(i + 1) / num_frames * 100:.1f}%)")

            if processed == 0:
                raise RecordingError("None of the frames could be read")
            encoder = writer.name
    finally:
        overlay.close()

    if unreadable:
        print(f"Warning: {unreadable} frame(s) could not be read and were skipped.")
    if resized:
        print(f"Warning: {resized} frame(s) differed from the first frame's size and were resized.")

    size_mb = Path(output_file).stat().st_size / (1024 * 1024)
    print(f"\nSuccess! Video created: {output_file}")
    print(f"   Encoder: {encoder}")
    print(f"   Processed {processed} frames")
    print(f"   File size: {size_mb:.2f} MB")


def main(argv=None):
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Create PiP video with live metrics graph from FlowLab recording",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python create_pip_video.py /path/to/recording/
  python create_pip_video.py ~/Documents/FlowLab3D/Recordings/2026_10_06_17_55_55/ --fps 25
        """,
    )
    parser.add_argument("recording_dir", help="Path to FlowLab recording directory")
    parser.add_argument(
        "--fps",
        type=int,
        default=DEFAULT_FPS,
        help=f"Output frames per second (default: {DEFAULT_FPS})",
    )
    args = parser.parse_args(argv)
    if args.fps <= 0:
        parser.error("--fps must be a positive integer")

    # Output goes into the recording directory, named after it.
    recording_dir = Path(args.recording_dir)
    output_file = recording_dir / f"{recording_dir.resolve().name}_pip.mp4"

    try:
        create_pip_video(recording_dir, output_file, args.fps)
    except RecordingError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())